sprint14/FirstVer/om-39-team-23/library/authentication/urls.py
from django.urls import  path
from . import views
app_name='authentication'
urlpatterns = [

    path('', views.signin,name="signin"),
    path('main/', views.main,name="main"),
    path('registration/', views.registration,name="registration"),
    path('',views.exit,name="exit"),
    path('users/',views.users,name="users"),
    path('user/<int:id>',views.get_user,name="get_user")


]

sprint14/FirstVer/om-39-team-23/library/author/urls.py
"""Defines URL patterns for author."""
from django.urls import path
from . import views

app_name = 'author'

urlpatterns = [
    # Home page
    path('', views.all_authors,name='all_authors'),
    path('create/', views.create,name="create"),

    path("delete/<int:id>/", views.delete, name = 'author'),
]

sprint14/FirstVer/om-39-team-23/library/book/urls.py
from django.urls import  path
from . import views
app_name='book'
urlpatterns = [

    path('', views.all_books,name="all_books"),
    path('about_book/<int:id>/', views.get_book,name="get_book"),
    path('search_book/', views.search_book,name="search_book"),

]

sprint14/FirstVer/om-39-team-23/library/library/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('books/',include('book.urls')),
    path('users/',include('authentication.urls')),
    path('orders/',include('order.urls')),
    path('author/', include('author.urls'))
]

sprint14/FirstVer/om-39-team-23/library/order/urls.py
from django.urls import  path
from . import views
app_name='order'
urlpatterns = [

    path('', views.all_orders,name="all_orders"),
    path('my_orders/', views.my_orders,name="my_orders"),
    path('new_orders/', views.new_orders,name="new_orders"),


]

sprint14/FirstVer/om-39-team-23/library/author/models.py
from django.db import models

import book.models


class Author(models.Model):
    """
        This class represents an Author. \n
        Attributes:
        -----------
        param name: Describes name of the author
        type name: str max_length=20
        param surname: Describes last name of the author
        type surname: str max_length=20
        param patronymic: Describes middle name of the author
        type patronymic: str max_length=20
    """
    name = models.CharField(blank=True, max_length=20)
    surname = models.CharField(blank=True, max_length=20)
    patronymic = models.CharField(blank=True, max_length=20)
    books = models.ManyToManyField(book.models.Book, related_name='authors')
    id = models.AutoField(primary_key=True)

    def __str__(self):
        """
        Magic method is redefined to show all information about Author.
        :return: author id, author name, author surname, author patronymic
        """
        return f"{self.name} {self.surname} {self.patronymic}"

    def __repr__(self):
        """
        This magic method is redefined to show class and id of Author object.
        :return: class, id
        """
        return f"{self.name} {self.surname}"

    @staticmethod
    def get_by_id(author_id):
        """
        :param author_id: SERIAL: the id of a Author to be found in the DB
        :return: author object or None if a user with such ID does not exist
        """
        # return Author.objects.filter(id=author_id)
        # return Author.get_by_id(author_id)
        # return  Author.get_object_or_404()
        try:
            return Author.objects.get(pk=author_id)
        except:
            return None

    @staticmethod
    def delete_by_id(author_id):
        """
        :param author_id: an id of a author to be deleted
        :type author_id: int
        :return: True if object existed in the db and was removed or False if it didn't exist
        """
        try:
            author = Author.objects.get(pk=author_id)
            author.delete()
            return True
        except:
            return False

    @staticmethod
    def create(name, surname, patronymic):
        """
        param name: Describes name of the author
        type name: str max_length=20
        param surname: Describes surname of the author
        type surname: str max_length=20
        param patronymic: Describes patronymic of the author
        type patronymic: str max_length=20
        :return: a new author object which is also written into the DB
        """
        if name and len(name) <= 20 and surname and len(surname) <= 20 and patronymic and len(patronymic) <= 20:
            author = Author(name=name, surname=surname, patronymic=patronymic)
            author.save()
            return author

    def to_dict(self):
        """
        :return: author id, author name, author surname, author patronymic
        :Example:
        | {
        |   'id': 8,
        |   'name': 'fn',
        |   'surname': 'mn',
        |   'patronymic': 'ln',
        | }
        """
        # return self.__dict__

    def update(self,
               name=None,
               surname=None,
               patronymic=None):
        """
        Updates author in the database with the specified parameters.\n
        param name: Describes name of the author
        type name: str max_length=20
        param surname: Describes surname of the author
        type surname: str max_length=20
        param patronymic: Describes patronymic of the author
        type patronymic: str max_length=20
        :return: None
        """

        if name and len(name) <= 20:
            self.name = name
        if surname and len(surname) <= 20:
            self.surname = surname
        if patronymic and len(patronymic) <= 20:
            self.patronymic = patronymic
        self.save()

    @staticmethod
    def get_all():
        """
        returns data for json request with QuerySet of all authors
        """
        return Author.objects.all()

sprint14/FirstVer/om-39-team-23/library/book/models.py
from django.db import models
import author.models
import datetime
from django.utils import timezone
class Book(models.Model):
    """
        This class represents an Author. \n
        Attributes:
        -----------
        param name: Describes name of the book
        type name: str max_length=128
        param description: Describes description of the book
        type description: str
        param count: Describes count of the book
        type count: int default=10
        param authors: list of Authors
        type authors: list->Author
    """
    name = models.CharField(blank=True, max_length=128)
    description = models.CharField(blank=True, max_length=256)
    count = models.IntegerField(default=10)
    year_of_publication = models.DateTimeField(null=True, blank=True, editable=True, default=timezone.now)
    date_of_issue  = models.DateTimeField(default=timezone.now, editable=True,null=True, blank=True)

    id = models.AutoField(primary_key=True)

    def __str__(self):
        """
        Magic method is redefined to show all information about Book.
        :return: book id, book name, book description, book count, book authors
        """
        return f"{self.name}"

    def __repr__(self):
        """
        This magic method is redefined to show class and id of Book object.
        :return: class, id
        """
        return f"Book(id={self.id})"

    @staticmethod
    def get_by_id(book_id):
        """
        :param book_id: SERIAL: the id of a Book to be found in the DB
        :return: book object or None if a book with such ID does not exist
        """
        return Book.objects.get(id=book_id) if Book.objects.filter(id=book_id) else None

    @staticmethod
    def delete_by_id(book_id):
        """
        :param book_id: an id of a book to be deleted
        :type book_id: int
        :return: True if object existed in the db and was removed or False if it didn't exist
        """
        if Book.get_by_id(book_id) is None:
            return False
        Book.objects.get(id=book_id).delete()
        return True

    @staticmethod
    def create(name, description, count=10, authors=None):
        """
        param name: Describes name of the book
        type name: str max_length=128
        param description: Describes description of the book
        type description: str
        param count: Describes count of the book
        type count: int default=10
        param authors: list of Authors
        type authors: list->Author
        :return: a new book object which is also written into the DB
        """
        if len(name) > 128:
            return None

        book = Book()
        book.name = name
        book.description = description
        book.count = count
        if (authors is not None):
            for elem in authors:
                book.authors.add(elem)
        book.save()
        return book

    def to_dict(self):
        """
        :return: book id, book name, book description, book count, book authors
        :Example:
        | {
        |   'id': 8,
        |   'name': 'django book',
        |   'description': 'bla bla bla',
        |   'count': 10',
        |   'authors': []
        | }
        """

    def update(self, name=None, description=None, count=None):
        """
        Updates book in the database with the specified parameters.\n
        param name: Describes name of the book
        type name: str max_length=128
        param description: Describes description of the book
        type description: str
        param count: Describes count of the book
        type count: int default=10
        :return: None
        """
        if name is not None:
            self.name = name

        if description is not None:
            self.description = description

        if count is not None:
            self.count = count

        self.save()

    def add_authors(self, authors):
        """
        Add  authors to  book in the database with the specified parameters.\n
        param authors: list authors
        :return: None
        """
        if (authors is not None):
            for elem in authors:
                self.authors.add(elem)
                self.save()

    def remove_authors(self, authors):
        """
        Remove authors to  book in the database with the specified parameters.\n
        param authors: list authors
        :return: None
        """
        for elem in self.authors.values():
            self.authors.remove(elem['id'])

    @staticmethod
    def get_all():
        """
        returns data for json request with QuerySet of all books
        """
        return list(Book.objects.all())

sprint14/FirstVer/om-39-team-23/library/author/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponseNotFound
from django.template.response import TemplateResponse
from .models import Author


def all_authors(request):
    '''Shows all authors'''
    authors = Author.objects.all()
    context = {'authors': authors}


    return render(request, 'authors.html', context=context)



def create(request):
    """Add new author to DB"""
    if request.method == "POST":
        Author.create(name=request.POST.get("name"),surname=request.POST.get("name"),patronymic=request.POST.get("patronymic"))

    return HttpResponseRedirect("/")
    #return render(request, 'author/authors.html')

# def edit(request, id):
#     """Edit authors"""
#     try:
#         author = Author.objects.get(id=id)
#
#         if request.method == "POST":
#             author.name = request.POST.get("name")
#             author.surname = request.POST.get("surname")
#             author.patronymic= request.POST.get("patronymic")
#             #author.books=request.POST.get("books")
#             author.save()
#             return HttpResponseRedirect("/")
#         else:
#             return render(request, "author/edit.html", {"author": author})
#     except Author.DoesNotExist:
#         return HttpResponseNotFound("<h2>Author not found</h2>")


def delete(request, id):
    """Delete author from DB"""
    try:
        author = Author.objects.get(id=id)
        author.delete()
        return HttpResponseRedirect("/")
    except Author.DoesNotExist:
        return HttpResponseNotFound("<h2>Author not found</h2>")


sprint14/FirstVer/om-39-team-23/library/book/views.py
from django.shortcuts import render,redirect
from book.models import Book
from django.db.models import Q
from author.models import Author
import logging
def all_books(request):
    context = {}

    context['books'] = Book.objects.order_by('id').all()

    return render(request, 'books.html', context=context)

def get_book(request, id):
    book = Book.objects.get(id=id)
    authors = book.authors.all()
    author = ", ".join([f"{i.name} {i.surname} {i.patronymic}" for i in authors])
    return render(request, 'about_book.html', {"book":book, "author":author})

def search_book(request):
    context = {}

    if request.method == "POST":

        logging.warning(f"{request.POST}")
        title = request.POST.get("query")
        if request.POST.get("author"):
            author_search = Author.objects.filter(Q(name__contains=title) | Q(surname__contains=title))
            context['authors'] = author_search
            context['find'] = True
        if request.POST.get('name') or request.POST.get('description') :
            book_search=Book.objects.filter(Q(name__contains=title) | Q(description__contains=title))
            context['books'] = book_search
            context['find'] = True


    return render(request, 'search_book.html', context=context)

sprint14/FirstVer/om-39-team-23/library/templates/about_book.html
{% extends "home.html" %}
{%block content%}
<h1>{{book.name}} In stock: {{ book.count }}</h1>
<p>{{book.description}}</p>
<br>
<h3>{{author}}</h3>
{%endblock%}

sprint14/FirstVer/om-39-team-23/library/templates/all_orders.html
{% extends "home.html" %}
{% block content %}
<form method="POST">{% csrf_token %}
<table class="table table-striped table-hover" style="LINE-HEIGHT:50px">

    <thead>
        <tr>
            <th scope="col">Number of Order</th>
            <th scope="col">Book Name</th>
          <th scope="col">First Name User</th>
            <th scope="col">Created at</th>
            <th scope="col">End at</th>
            <th scope="col">Plated end at</th>
        </tr>
    </thead>

  {% for row in orders %}

    <tr  >
      <td >{{ row.id }}</td>
      <td ><a href="{% url 'book:get_book' id=row.book__id %}" class="link-dark">{{ row.book__name }}</a></td>
      <td ><a href="{% url 'authentication:get_user' id=row.user__id %}" class="link-dark">{{ row.user__first_name }}  </a></td>

        <td >{{ row.created_at }}</td>
        <td >{{ row.end_at }}</td>
        <td >{{ row.plated_end_at }}</td>

        <td><button formaction="{% url 'order:all_orders' %}" name="order_id" value="{{row.id}}"  type="submit">Close Order</button></td>

    </tr>
  {%endfor%}
</table>
</form>
{% endblock %}

sprint14/FirstVer/om-39-team-23/library/templates/authors.html
{% extends "home.html" %}
{% block content %}
<form method="POST" action="{% url 'author:create' %}">
        {% csrf_token %}
        <p>
            <label>Enter a name</label><br>
            <input type="text" name="name" />
        </p>
        <p>
            <label>Enter a surname</label><br>
            <input type="text" name="surname" />
        </p>
        <p>
            <label>Enter a patronymic</label><br>
            <input type="text" name="patronymic" />
        </p>
        <input type="submit" value="Save" >
    </form>
    {% if authors.count > 0 %}
    <h2>AUTHORS</h2>
    <table>
        <thead><tr><th>Id</th><th>Name</th><th>Surname</th><th>Patronymic</th></tr></thead>
        {% for author in authors %}
        <tr>
            <td>{{ author.id }}</td>
            <td>{{ author.name }}</td>
            <td>{{ author.surname }}</td>
            <td>{{ author.patronymic }}</td>

            <td><a href="delete/{{author.id}}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}

{% endblock %}

sprint14/FirstVer/om-39-team-23/library/templates/base.html

{% load static %}
<!doctype html>

<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/styles_auth.css' %}" >
</head>
<body>
{% block content %}
{%endblock%}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

sprint14/FirstVer/om-39-team-23/library/templates/books.html
{% extends "home.html" %}
{% load extra_fun %}
{% load static %}
{%block content%}
<link rel="stylesheet" href="{% static 'css/books.css' %}">
<table class="table table-striped table-hover" style="LINE-HEIGHT:50px">

    <thead>
        <tr>
            <th scope="col">Number of Books</th>
            <th scope="col">Name</th>
          <th scope="col">Authors</th>
        </tr>
    </thead>

  {% for row in books %}

    <tr  >
      <td >{{ row.id }}</td>
      <td ><a href="{% url 'book:get_book' id=row.id %}" class="link-dark">{{ row.name }}</a></td>
      <td >{{ row|list_authors }}</td>
    </tr>
  {%endfor%}
</table>
<a class="btn btn-dark" target="_blank" href="{% url 'book:search_book' %}">Search Book</a>
{%endblock%}



sprint14/FirstVer/om-39-team-23/library/templates/create_order.html
{% extends "home.html" %}
{% block content %}
<section class="vh-100 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row justify-content-center align-items-center h-100">
      <div class="col-12 col-lg-9 col-xl-7">
        <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
          <div class="card-body p-4 p-md-5">
            <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">Create New Order</h3>
            <form method="POST" action="{% url 'order:new_orders' %}">{% csrf_token %}
            <div class="row">
             <select name="book_id" id="form3Example4cdg" >
                          {% for book in books %}
                            <option value="{{ book.id }}">{{book.name}}</option>
                          {% endfor %}
             </select>

              </div>
                <div class="row">
              <div class="form-outline mb-4">
                      <input type="datetime-local" id="form3Example4cg" class="form-control form-control-lg" name="planed_end"/>
                      <label class="form-label" for="form3Example4cg" style="margin-top:10px;">Planed End</label>
                    </div>
                </div>
                <div class="row">
                    <div class="d-flex justify-content-center">
                      <button type="submit"
                        class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">Create</button>
                    </div>
                </div>
            </form>
          </div>
      </div>
      </div>
  </div>
  </div>
</section>

{% endblock %}

sprint14/FirstVer/om-39-team-23/library/templates/home.html
{% include "base.html" %}

<header>
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-white">
    <div class="container-fluid">
      <button
        class="navbar-toggler"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#navbarExample01"
        aria-controls="navbarExample01"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarExample01">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item active">
            <a class="nav-link" aria-current="page" href="{% url 'authentication:main' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'book:all_books' %}">Books</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'author:all_authors'%}">Authors</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'order:all_orders'%}">Orders</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'order:my_orders'%}">My Orders</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'order:new_orders'%}">Create Orders</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'authentication:users' %}">Users</a>
          </li>
           <li class="nav-item">
          <a class="nav-link" href="{% url 'authentication:exit' %}">Log out</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- Navbar -->


  <!-- Background image -->
</header>
<section class="vh-100 gradient-custom">

{% block content %}
{%endblock%}
</section>






sprint14/FirstVer/om-39-team-23/library/templates/login.html
{% extends "base.html" %}
{% block content %}


 <section class="vh-100 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card bg-dark text-white" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">

            <div class="mb-md-5 mt-md-4 pb-5">
            <form method="POST" action="{% url 'authentication:signin' %}" >{% csrf_token %}
              <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
              <p class="text-white-50 mb-5">Please enter your login and password!</p>

              <div class="form-outline form-white mb-4">
                <input type="email" name="email" id="typeEmailX" class="form-control form-control-lg" />
                <label class="form-label" for="typeEmailX">Email</label>
              </div>

              <div class="form-outline form-white mb-4">
                <input type="password" name="password" id="typePasswordX" class="form-control form-control-lg" />
                <label class="form-label" for="typePasswordX">Password</label>
              </div>

              <button  class="btn btn-outline-light btn-lg px-5" type="submit">Login</button>
            </form>
              <div class="d-flex justify-content-center text-center mt-4 pt-1">
                <a href="#!" class="text-white"><i class="fab fa-facebook-f fa-lg"></i></a>
                <a href="#!" class="text-white"><i class="fab fa-twitter fa-lg mx-4 px-2"></i></a>
                <a href="#!" class="text-white"><i class="fab fa-google fa-lg"></i></a>
              </div>

            </div>

            <div>
              <p class="mb-0">Don't have an account? <a href="/registration" class="text-white-50 fw-bold">Sign Up</a>
              </p>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{%endblock%}

sprint14/FirstVer/om-39-team-23/library/templates/my_orders.html
{% extends "home.html" %}
{% block content %}
<table class="table table-striped table-hover" style="LINE-HEIGHT:50px">

    <thead>
        <tr>
            <th scope="col">Number of Order</th>
            <th scope="col">Book Name</th>
            <th scope="col">Created at</th>
            <th scope="col">End at</th>
            <th scope="col">Plated end at</th>
        </tr>
    </thead>

  {% for row in orders %}

    <tr  >
      <td >{{ row.id }}</td>
      <td ><a href="{% url 'book:get_book' id=row.book__id %}" class="link-dark">{{ row.book__name }}</a></td>
        <td >{{ row.created_at }}</td>
        <td >{{ row.end_at }}</td>
        <td >{{ row.plated_end_at }}</td>
    </tr>
  {%endfor%}
</table>
{% endblock %}

sprint14/FirstVer/om-39-team-23/library/templates/registration.html
{% extends "base.html" %}
{% block content %}
<section class="vh-100 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row justify-content-center align-items-center h-100">
      <div class="col-12 col-lg-9 col-xl-7">
        <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
          <div class="card-body p-4 p-md-5">
            <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">Registration Form</h3>
            <form method="POST" action="{% url 'authentication:registration' %}">{% csrf_token %}

              <div class="row">
                <div class="col-md-6 mb-4">

                  <div class="form-outline">
                    <input type="text" name="first_name" class="form-control form-control-lg" />
                    <label class="form-label" >First Name</label>
                  </div>

                </div>
                <div class="col-md-6 mb-4">

                  <div class="form-outline">
                    <input type="text" name="last_name" class="form-control form-control-lg" />
                    <label class="form-label" >Last Name</label>
                  </div>

                </div>
              </div>

              <div class="row">
                <div class="col-md-6 mb-4 d-flex align-items-center">

                  <div class="form-outline">
                    <input type="text" class="form-control form-control-lg" name="middle_name" />
                    <label  class="form-label" >Middle Name</label>
                  </div>

                </div>
                <div class="col-md-6 mb-4">

                  <h6 class="mb-2 pb-1">Role: </h6>

                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="role" id="roleUser"
                      value=0 checked />
                    <label class="form-check-label" for="roleUser">User</label>
                  </div>

                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="role" id="roleLibrarian"
                      value=1 />
                    <label class="form-check-label" for="roleLibrarian">Librarian</label>
                  </div>

                </div>
              </div>

              <div class="row">
                <div class="col-md-6 mb-4 pb-2">

                  <div class="form-outline">
                    <input type="email" id="emailAddress" name="email" class="form-control form-control-lg" />
                    <label class="form-label" for="emailAddress">Email</label>
                  </div>

                </div>
              </div>
              <div class="row">
                <div class="col-md-6 mb-4 pb-2">

                  <div class="form-outline">
                    <input type="password" id="password" name="password" class="form-control form-control-lg" />
                    <label class="form-label" for="password">Password</label>
                  </div>

                </div>
              </div>
              <div class="row">
                <div class="col-md-6 mb-4 pb-2">

              <div class="mt-4 pt-2">
                <input class="btn btn-primary btn-lg" type="submit" value="Submit" />
              </div>

            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}


sprint14/FirstVer/om-39-team-23/library/templates/search_book.html
{% extends "home.html" %}
{% load extra_fun %}
{%block content%}

<form method="POST" action="{% url 'book:search_book' %}" >{%csrf_token%}
    <div class="form-group" style="padding-right:83%;">
    <label for="exampleInputSearch">Email address</label>
    <input name="query" type="search" class="form-control" id="exampleInputSearch" aria-describedby="Help" placeholder="Enter query">
    <small id="Help" class="form-text text-muted">Select a filter to search for a specific key value</small>
  </div>
<div class="form-check" >
  <input name="author" class="form-check-input" type="checkbox" value="author" id="flexCheckDefault">
  <label class="form-check-label" for="flexCheckDefault">
    by Author
  </label>
</div>
<div class="form-check" >
<input name="name" class="form-check-input" type="checkbox" value="name" id="flexCheckChecked" >
  <label class="form-check-label" for="flexCheckChecked">
    by Name
  </label>
</div>
    <div class="form-check" >
    <input name="descr" class="form-check-input" type="checkbox" value="descr" id="flexCheck" >
  <label class="form-check-label" for="flexCheck">
    by Description
  </label>
    </div>


    <button value="Submit" type="submit" class="btn btn-dark">Search</button>
</form>
{% if find %}
<table class="table table-striped table-hover" style="LINE-HEIGHT:50px">
    <thead>
        <tr>
            <th scope="col">Number of Books</th>
            <th scope="col">Name</th>
          <th scope="col">Authors</th>
        </tr>
    </thead>
  {% for row in books %}
    <tr  >
      <td >{{ row.id }}</td>
      <td ><a href="{% url 'book:get_book' id=row.id %}" class="link-dark">{{ row.name }}</a></td>
      <td >{{ row|list_authors }}</td>
    </tr>
  {%endfor%}
    {% for row in authors %}
    <tr  >
      <td >{{ row.id }}</td>
      <td ><a href="{% url 'book:get_book' id=row.id %}" class="link-dark">{{ row|list_books }}</a></td>
      <td >{{ row.name }} {{ row.surname }}</td>
    </tr>
  {%endfor%}

</table>
{% endif %}
{%endblock%}

sprint14/FirstVer/om-39-team-23/library/templates/user_page.html
{% extends "home.html" %}

  {% block content %}
  <h1>{{ user.first_name }} {{user.middle_name}} {{user.last_name}}</h1>
  <h5>ID:{{ user.id }}</h5>
  <h3 >Email{{ user.email }}</h3>
  <h3 >Last on OnLine{{ user.last_login }}</h3>
  <h3 >{{ user.role }}</h3>
{% endblock %}

sprint14/FirstVer/om-39-team-23/library/templates/users.html
{% extends "home.html" %}
{% block content %}
<table class="table table-striped table-hover" style="LINE-HEIGHT:50px">

    <thead>
        <tr>
            <th scope="col">Number of User</th>
            <th scope="col">Name</th>
          <th scope="col">Email</th>
            <th scope="col">Last Login</th>
            <th scope="col">Role</th>
        </tr>
    </thead>

  {% for row in users %}

    <tr  >
      <td >{{ row.id }}</td>
      <td ><a href="{% url 'authentication:get_user' id=row.id %}" class="link-dark">{{ row.first_name }} {{row.middle_name}} {{row.last_name}}</a></td>
      <td >{{ row.email }}</td>
        <td >{{ row.last_login }}</td>
        <td >{{ row.role }}</td>
    </tr>
  {%endfor%}
</table>
{% endblock %}